
name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Fazer Deploy no GitHub
        run: |
          echo "Rodando o deploy diretamente no GitHub..."
          # Coloque os comandos que fazem o deploy aqui, se necessário
